
services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - ollama
    volumes:
      - ./app:/app
      - ./chroma:/chroma

  redis:
    image: redis:7
    ports:
      - "6379:6379"

